typography_spectrum: 0.01603
color:
  brandColors:
    - '#0f5c9f'
    - '#f7f7f7'
    - '#0e1317'
    - '#4991d5'
    - '#e680af'
  brandStrength: 0.5
  lightness: 0.983917540172115
  saturation: 0.5
  rhythmicContrast: 0.9453508453443646
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.34692
analytics:
  google: null
  facebook: null
  twitter: null
name: photostory-prateekseksaria
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Germany
purpose: []
